const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
        info: {
            title: 'A La Cruz API',
            description: 'Test API with autogenerated swagger doc',
            version: '1.0.0',
        },
    },
    apis: ['./routes/*.js'],
    basePath: '/'
};
const specs = swaggerJsdoc(options);
module.exports = specs;
